name: CI Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # Use the LTS version of Node.js
          cache: 'npm' # Enable npm cache for faster installation

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      # Step 4: Run linter (ESLint)
      - name: Run ESLint
        run: npm run lint

      # Step 5: Run unit tests
      - name: Run unit tests
        run: npm run test

      # Step 6: Check test coverage (optional)
      - name: Check test coverage
        run: npm run test:cov
